apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
