version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/deploy

hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
